### PR TITLE
Add option to show FPS counter and performance statistics

### PR DESCRIPTION
**Pull request by keton**
This commit adds to debug menu toggle to show Unreal Engine FPS counter and engine statistics.

This provides non obnoxious way to have them on screen at all times. Stats appear in top left corner just outside of your normal field of vision. This allows you to turn them on and keep them on compared to Virtual Desktop overlay.

Compared to OpenXR toolkit this way is much more compatible with UEVR. Current builds of OpenXR increase number of crashes.

EDIT: after testing in quite some games it looks like devs can block this in release builds and customize overlay locations. But one of 2 added options always worked with exception of "Deliver us Mars" which has some bigger issue with UEVR.

### CODE REVIEW

**Comment by praydog** [comment]
Are you able to verify in the games that you had issues with that they have actually blocked it? It could just be UEVR failing to locate the Exec function. You can use the "show native console" and press ~ to try and enter it manually, or use something like UUU to enable it.

**Comment by keton** [comment]
> Are you able to verify in the games that you had issues with that they have actually blocked it?

No. I've just assumed that if it's not working it must be disabled somehow. That plus seeing that most overlay positions are customized and make sense from game UI placement standpoint.

I've tried UE4SS in 3 different games to see what is possible. I've also tried all `stat` commands I could find. Really wanted `stat unitgraph` to work but no dice. There was a version of this patch that had it but 0 games I've tested worked. You might be right with mod tools failing to find right function addresses.

UUU versions I've tried in general crash the game more than anything. Similarly 'spawn native console' in UEVR ended in a crash in all my attempts. Will play with that some more.

**Comment by mark-mon** [comment]
As this just uses exec, I assume there's no way to control the font size? It's sure tiny in some cases.

**Comment by keton** [comment]
Point of this approach is not to mess with game code. So no either something shows up or not. And so far in every game that it works it's apparent someone took a moment to put it in a place that does not collide with anything. Font is visible enough unless you also bind UI to hand movement but then you can bring the counters in front of your eyes. Worst case you can peek on your monitor.

At this point I've literally checked every UE game I have installed and the only problem is that in some of them `stat fps` does nothing but `stat unit` works in such cases. It's maybe not optimal as you need to know that 11ms == 90fps. IMO better than nothing or OpenXR that forces me to press ctrl+f2 for each game (I don't play VR close to my PC).

**Comment by mark-mon** [comment]
I really like the change. It's really useful for testing new games and figuring out what your system can handle or not. Thanks again for making it. Let's hope it's merged in soon in the meantime I built your branch.

**Pull request merged**
